version: 2
machine:
  node:
    version: 6.9.5
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
jobs:
  build:
    steps:
      - run: create
