branch-defaults:
  master:
    environment: firstenv
environment-defaults:
  firstenv:
    branch: null
    repository: null
global:
  application_name: tester
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Node.js running on
    64bit Amazon Linux/4.1.0
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
